% Plot TSAT
MTB = dlmread('MTB.42');
BNB = dlmread('MTB.42');
WBN = dlmread('WBN.42');
QBN = dlmread('QBN.42');
POSN = dlmread('POSN.42');
ILLUM = dlmread('ILLUM.42');
ALBEDO = dlmread('Albedo.42');
HWHL = dlmread('Hwhl.42');
SVB = dlmread('SVB.42');
figure(2);clf;
orbit=(1:length(POSN))/(96.77*60);xlabel('Orbits');
plot(orbit,POSN(:,3));hold on;grid on;title('POSN');
figure(1);clf;
subplot(3,1,1);
plot(orbit,MTB);hold on;grid on;title('MTB');xlabel('Orbits');
subplot(3,1,2);
plot(orbit,WBN);hold on;grid on;title('WBN');xlabel('Orbits');
subplot(3,1,3);
plot(orbit,QBN(:,1:3));hold on;grid on;title('QBN');
plot(orbit,QBN(:,4),'k');hold on;grid on;title('QBN');xlabel('Orbits');
figure(3);clf;
orbit=(1:length(POSN))/(96.77*60);xlabel('Orbits');
plot(orbit,QBN(:,1:3)*180/pi);hold on;grid on;
title('QBN(0:2) [deg]');
figure(4);clf;
iiv=find(max(ILLUM')>0.);
plot(orbit(iiv),SVB(iiv,1),'r.');hold on;
plot(orbit(iiv),SVB(iiv,2),'g.');hold on;
plot(orbit(iiv),SVB(iiv,3),'b.');hold on;
grid on;title('SVB');
xlabel('Orbits');
figure(41);clf;
plot3(SVB(iiv,1),SVB(iiv,2),SVB(iiv,3),'k.');hold on;
figure(5);clf;
plot(orbit,ILLUM(:,1),'r');hold on;
plot(orbit,ILLUM(:,2),'r--');hold on;
plot(orbit,ILLUM(:,3),'g');hold on;
plot(orbit,ILLUM(:,4),'g--');hold on;
plot(orbit,ILLUM(:,5),'b');hold on;
plot(orbit,ILLUM(:,6),'b--');hold on;
plot(orbit,ILLUM(:,7),'m');hold on;
plot(orbit,ILLUM(:,8),'m--');hold on;
plot(orbit,ILLUM(:,9),'c');hold on;
plot(orbit,ILLUM(:,10),'c--');hold on;
%plot(orbit,ILLUM(:,11),'k');hold on;
%plot(orbit,ILLUM(:,12),'k--');hold on;
figure(6);clf;
title('Wheel Speed[RPM]');hold on;grid on;
plot(HWHL(:,1)/2.1128e-6,'r');hold on;
plot(HWHL(:,2)/2.1128e-6,'g');hold on;
plot(HWHL(:,3)/2.1128e-6,'b');hold on;
%plot(orbit,HWHL(:,4)/2.1128e-6,'k');hold on;